trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'
      
variables:
  dockerfilePath: 'app/Dockerfile'
  imageRepository: 'pipelines-javascript-docker'

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
